"""Adiciona coluna imagem no Terco

Revision ID: b1a9d63f969a
Revises: 4e7700f68fe4
Create Date: 2025-05-24 20:43:35.727403

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b1a9d63f969a'
down_revision = '4e7700f68fe4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('novena')
    op.drop_table('terco')
    op.drop_table('rosario')
    op.drop_table('oracao')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('oracao',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('titulo', sa.VARCHAR(length=200), nullable=False),
    sa.Column('descricao', sa.TEXT(), nullable=True),
    sa.Column('conteudo', sa.TEXT(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rosario',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('titulo', sa.VARCHAR(length=200), nullable=False),
    sa.Column('descricao', sa.TEXT(), nullable=True),
    sa.Column('conteudo', sa.TEXT(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('terco',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('titulo', sa.VARCHAR(length=100), nullable=False),
    sa.Column('descricao', sa.TEXT(), nullable=False),
    sa.Column('conteudo', sa.TEXT(), nullable=False),
    sa.Column('imagem', sa.VARCHAR(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('novena',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('titulo', sa.VARCHAR(length=200), nullable=False),
    sa.Column('descricao', sa.TEXT(), nullable=True),
    sa.Column('conteudo', sa.TEXT(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
